PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS responsible_abstraction_check;
DROP TABLE IF EXISTS abstraction_risk;
DROP TABLE IF EXISTS diagram_record;
DROP TABLE IF EXISTS universal_property_record;
DROP TABLE IF EXISTS natural_transformation_record;
DROP TABLE IF EXISTS functor_record;
DROP TABLE IF EXISTS category_record;

CREATE TABLE category_record (
  category_id TEXT PRIMARY KEY,
  category_name TEXT NOT NULL,
  objects TEXT NOT NULL,
  morphisms TEXT NOT NULL,
  preserved_structure TEXT NOT NULL,
  composition_rule TEXT NOT NULL,
  abstraction_risk TEXT NOT NULL
);

CREATE TABLE functor_record (
  functor_id TEXT PRIMARY KEY,
  functor_name TEXT NOT NULL,
  source_category TEXT NOT NULL,
  target_category TEXT NOT NULL,
  object_mapping TEXT NOT NULL,
  morphism_mapping TEXT NOT NULL,
  preserved_property TEXT NOT NULL,
  forgotten_or_added_structure TEXT NOT NULL
);

CREATE TABLE natural_transformation_record (
  transformation_id TEXT PRIMARY KEY,
  transformation_name TEXT NOT NULL,
  source_functor TEXT NOT NULL,
  target_functor TEXT NOT NULL,
  component_description TEXT NOT NULL,
  naturality_condition TEXT NOT NULL,
  coherence_review TEXT NOT NULL
);

CREATE TABLE universal_property_record (
  property_id TEXT PRIMARY KEY,
  construction_name TEXT NOT NULL,
  diagram_shape TEXT NOT NULL,
  universal_role TEXT NOT NULL,
  uniqueness_condition TEXT NOT NULL,
  example_domain TEXT NOT NULL,
  review_question TEXT NOT NULL
);

CREATE TABLE diagram_record (
  diagram_id TEXT PRIMARY KEY,
  diagram_name TEXT NOT NULL,
  diagram_type TEXT NOT NULL,
  path_left TEXT NOT NULL,
  path_right TEXT NOT NULL,
  commutativity_condition TEXT NOT NULL,
  interpretation TEXT NOT NULL
);

CREATE TABLE abstraction_risk (
  risk_id TEXT PRIMARY KEY,
  risk_name TEXT NOT NULL,
  problem TEXT NOT NULL,
  mitigation TEXT NOT NULL
);

CREATE TABLE responsible_abstraction_check (
  check_id TEXT PRIMARY KEY,
  stage TEXT NOT NULL,
  question TEXT NOT NULL,
  failure_mode TEXT NOT NULL,
  mitigation TEXT NOT NULL
);

INSERT INTO category_record VALUES
('cat_set','Set','sets','functions','element assignment','function composition','ignoring additional structure such as topology or algebra'),
('cat_grp','Grp','groups','group homomorphisms','group operation','composition of homomorphisms','forgetting that not every function between groups is a homomorphism'),
('cat_top','Top','topological spaces','continuous maps','topological continuity','composition of continuous maps','confusing set-theoretic maps with continuous maps'),
('cat_vect','Vect','vector spaces','linear maps','addition and scalar multiplication','composition of linear transformations','hiding basis-dependent computational details'),
('cat_poset','Poset','partially ordered sets','monotone maps','order relation','composition of order-preserving maps','ignoring order-theoretic edge cases'),
('cat_type','Type','types','typed functions','computational typing and behavior','typed function composition','confusing mathematical functions with implemented programs');

INSERT INTO functor_record VALUES
('fun_underlying_group','Underlying set of a group','Grp','Set','send a group to its underlying set','send a group homomorphism to its underlying function','composition and identity of maps','forgets group operation'),
('fun_free_group','Free group on a set','Set','Grp','send a set to the free group generated by it','extend functions uniquely to homomorphisms','universal extension behavior','adds group structure freely'),
('fun_homology','Homology functor','Top','Ab','send a space to algebraic homology groups','send continuous maps to induced homomorphisms','topological information through algebraic invariants','forgets many geometric details while preserving selected invariants'),
('fun_power_set','Power set construction','Set','Set','send a set to its set of subsets','map subsets by direct or inverse image depending on variance','subset construction behavior','changes level from elements to collections of elements'),
('fun_data_migration','Schema migration functor','SchemaA','SchemaB','send entities in one schema to corresponding entities in another','send relationships to relationship-preserving mappings','schema structure and compositional relationships','may lose context, provenance, or semantic nuance');

INSERT INTO natural_transformation_record VALUES
('nat_double_dual','Vector space to double dual','Identity on finite-dimensional vector spaces','Double-dual functor','map each vector to evaluation on linear functionals','commutes with linear maps in the finite-dimensional setting','confirm dimensional assumptions and map naturality'),
('nat_unit_adjunction','Unit of free-forgetful adjunction','Identity on Set','Underlying-set after free-group functor','send each generator into the underlying set of the free group','commutes with functions between generating sets','confirm naturality with respect to generator maps'),
('nat_data_view','Data view transformation','Raw schema instance functor','Curated schema instance functor','map raw records into cleaned view records','commutes with schema relationship mappings','review whether cleaning preserves intended relationships');

INSERT INTO universal_property_record VALUES
('up_product','Product','cone to two objects','universal object mapping to both factors','any compatible pair of maps factors uniquely through the product','sets, groups, vector spaces, spaces','what maps into the construction and what projections are required?'),
('up_coproduct','Coproduct','cocone from two objects','universal object receiving maps from both summands','any compatible pair of maps out factors uniquely from the coproduct','sets, groups, types, spaces','what maps out of the construction and what injections are required?'),
('up_pullback','Pullback','compatible square over shared target','universal object enforcing agreement over a target','any compatible cone factors uniquely through the pullback','sets, spaces, schemas, systems','which compatibility relation is being enforced?'),
('up_pushout','Pushout','cospan glued along shared source','universal object combining structures along shared data','any compatible cocone factors uniquely from the pushout','spaces, schemas, algebraic structures, systems','what is being glued and what identifications are introduced?'),
('up_free_object','Free object','adjunction unit or universal extension','most general structured object generated from input data','maps from generators extend uniquely to structure-preserving maps','free groups, free vector spaces, free monoids','what structure is freely added and what constraints remain absent?');

INSERT INTO diagram_record VALUES
('diag_square','Commutative square','square','g after f','k after h','g∘f = k∘h','two routes through the diagram yield the same morphism'),
('diag_triangle','Factorization triangle','triangle','u followed by projection','given map','projection∘u = given map','a universal map factors a given compatible family'),
('diag_naturality','Naturality square','square','eta_B after F(f)','G(f) after eta_A','eta_B∘F(f) = G(f)∘eta_A','comparison between functors respects morphisms in the source category'),
('diag_adjunction','Adjunction correspondence','hom-set correspondence','Hom_D(F(A),B)','Hom_C(A,G(B))','natural bijection of hom-sets','two ways of specifying a map correspond naturally');

INSERT INTO abstraction_risk VALUES
('risk_premature_abstraction','Premature abstraction','categorical language appears before examples motivate it','build from concrete categories and recurring patterns'),
('risk_overgeneralization','Overgeneralization','shared categorical form hides important domain differences','ask what the functor preserves and what it forgets'),
('risk_decorative_diagram','Decorative diagrams','diagrams appear without proof-bearing content','state commutativity and universal properties explicitly'),
('risk_jargon_inflation','Jargon inflation','terms replace understanding','translate categorical language back into examples'),
('risk_computational_neglect','Computational neglect','universal characterization hides algorithmic cost','pair categorical structure with implementation analysis'),
('risk_forgotten_structure','Forgotten structure','a functor preserves one structure while forgetting another','document preserved and forgotten features'),
('risk_modeling_blindspot','Modeling blind spot','formal structure hides social, ecological, institutional, or contextual realities','document assumptions, exclusions, stakeholders, and consequences');

INSERT INTO responsible_abstraction_check VALUES
('check_objects','Objects','What entities or structures are being studied?','unclear domain of discourse','define objects and concrete examples before abstraction'),
('check_arrows','Arrows','What transformations are allowed?','wrong or vague notion of relationship','state morphisms and what they preserve'),
('check_structure','Structure','What do the arrows preserve or forget?','important features are forgotten','document preserved and forgotten structure'),
('check_universality','Universality','What role does the construction satisfy among all maps?','construction understood only by recipe, not by role','state the universal mapping property and uniqueness condition'),
('check_responsibility','Responsibility','What happens if this abstraction is used in a real system?','formal elegance hides consequences','document assumptions, limits, implementation costs, and affected contexts');
