PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS algebraic_misconception;
DROP TABLE IF EXISTS function_representation;
DROP TABLE IF EXISTS equation_audit;
DROP TABLE IF EXISTS transformation_rule;
DROP TABLE IF EXISTS variable_role;
DROP TABLE IF EXISTS algebraic_object;

CREATE TABLE algebraic_object (
  object_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  object_type TEXT NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE variable_role (
  role_id TEXT PRIMARY KEY,
  symbol TEXT NOT NULL,
  role_type TEXT NOT NULL,
  example TEXT NOT NULL,
  interpretation TEXT NOT NULL
);

CREATE TABLE transformation_rule (
  rule_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  source_form TEXT NOT NULL,
  target_form TEXT NOT NULL,
  preserved_meaning TEXT NOT NULL,
  risk_note TEXT NOT NULL
);

CREATE TABLE equation_audit (
  equation_id TEXT PRIMARY KEY,
  equation_text TEXT NOT NULL,
  equation_type TEXT NOT NULL,
  interpretation TEXT NOT NULL,
  verification_method TEXT NOT NULL
);

CREATE TABLE function_representation (
  function_id TEXT NOT NULL,
  representation_type TEXT NOT NULL,
  representation_text TEXT NOT NULL,
  preserved_structure TEXT NOT NULL,
  possible_limitation TEXT NOT NULL,
  PRIMARY KEY (function_id, representation_type)
);

CREATE TABLE algebraic_misconception (
  misconception_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  diagnostic_signal TEXT NOT NULL,
  intervention TEXT NOT NULL
);

INSERT INTO algebraic_object VALUES
('obj_expression_factored','Factored linear expression','expression','The expression 2(x+3), which reveals factor and grouping structure.'),
('obj_expression_expanded','Expanded linear expression','expression','The expression 2x+6, which reveals term structure.'),
('obj_equation_linear','Linear equation','equation','The equation 3x+2=17, interpreted as a condition on x.'),
('obj_function_linear','Linear function','function','The function f(x)=3x+2, interpreted as dependence of output on input.'),
('obj_identity_distributive','Distributive identity','identity','The identity a(b+c)=ab+ac, expressing structural relation between operations.'),
('obj_sequence_arithmetic','Arithmetic sequence','sequence','A sequence generated by a constant difference and represented algebraically.'),
('obj_structure_group','Group-like structure','algebraic_structure','A system with an operation, identity, inverses, and associativity.');

INSERT INTO variable_role VALUES
('role_unknown','x','unknown','x+3=10','x is a value to be determined.'),
('role_generalized_number','n','generalized_number','n+n=2n','n represents an arbitrary number in a domain.'),
('role_input','x','function_input','f(x)=3x+2','x is an input value for a function.'),
('role_output','y','function_output','y=3x+2','y depends on x through a rule.'),
('role_parameter','m','parameter','y=mx+b','m controls slope in a family of lines.'),
('role_index','n','index','a_n=2n+1','n marks position in a sequence.'),
('role_coefficient','a','coefficient','ax^2+bx+c','a controls the quadratic term.');

INSERT INTO transformation_rule VALUES
('rule_expand','Expand','2(x+3)','2x+6','expression value for all x in the domain','expanded form may hide factors'),
('rule_factor','Factor','x^2+5x+6','(x+2)(x+3)','expression value and zeros when domain is appropriate','factorization depends on coefficient domain'),
('rule_add_both_sides','Add to both sides','x-4=8','x=12','solution set under standard equality operations','usually safe in standard algebraic systems'),
('rule_divide_expression','Divide by expression','x(x-1)=0','x-1=0','conditional implication only if divided expression nonzero','can lose solutions when divisor may be zero'),
('rule_square_both_sides','Square both sides','x=3','x^2=9','truth of original implies transformed equation','can introduce extraneous solutions'),
('rule_complete_square','Complete the square','x^2+6x+5','(x+3)^2-4','expression value for all x','may obscure roots unless interpreted');

INSERT INTO equation_audit VALUES
('eq_linear_solve','3x+2=17','conditional_equation','Find x values satisfying the condition.','substitute candidate into original equation'),
('eq_identity_square','(x+1)^2=x^2+2x+1','identity','True for all x in the polynomial domain.','expand or compare coefficients'),
('eq_circle','x^2+y^2=1','geometric_relation','Defines the unit circle in the plane.','check point satisfies relation'),
('eq_function','y=3x+2','function_relation','Defines dependence of y on x.','evaluate inputs and compare outputs'),
('eq_model','C=50+12n','model_equation','Represents fixed cost plus variable cost.','check units assumptions and context');

INSERT INTO function_representation VALUES
('f_linear','verbal_rule','start at 2 and add 3 for each increase in x','process and rate of change','less compact for algebraic manipulation'),
('f_linear','table','(0,2) (1,5) (2,8) (3,11)','sampled input-output pairs','finite sample does not establish full rule'),
('f_linear','formula','f(x)=3x+2','general symbolic rule','domain and codomain may be hidden'),
('f_linear','graph','line with slope 3 and intercept 2','shape and rate of change','scale may distort visual interpretation'),
('f_linear','code','lambda x: 3*x+2','executable rule','implementation must match mathematical definition');

INSERT INTO algebraic_misconception VALUES
('mis_equal_sign_answer','Equal sign as answer signal','Treating equals as meaning the answer comes next.','student rejects 8+4=10+2','use relational true-false equations and balance models'),
('mis_variable_unknown_only','Variable as unknown only','Treating every variable as a value to solve for.','student tries to solve a+b=b+a','compare unknown generalized number parameter and input roles'),
('mis_cancel_invalid','Invalid cancellation','Canceling symbols without preserving equivalence.','student cancels x in x+2 over x+3','use numerical tests and domain-aware transformation rules'),
('mis_examples_proof','Examples as proof','Treating checked cases as proof of an identity.','student says it works for five values so always true','introduce counterexamples and symbolic proof'),
('mis_extraneous_solutions','Extraneous solutions','Accepting candidates introduced by non-equivalent transformations.','student squares both sides and does not check','require substitution into original equation'),
('mis_expression_equation_confusion','Expression-equation confusion','Confusing simplifying an expression with solving an equation.','student tries to solve 2x+6 without condition','separate expression evaluation transformation and equation solving');
